/**
 * Cleverguys Platformasi — Savollar Bazasi Fayli (questions.js)
 * Jami: 18 ta fan, har bir fanda 25 tadan professional test savoli (Jami 450 ta savol).
 * * Tuzilishi:
 * s: Savol matni
 * a: Javob variantlari [A, B, C]
 * c: To'g'ri javob indeksi (0, 1 yoki 2)
 */

const subjectsData = [
    {
        id: 'math', name: 'Matematika', icon: '🧮',
        q: [
            { s: "Amallarni bajaring: 5 + 5 × 5 - 5 = ?", a: ["45", "25", "20"], c: 1 },
            { s: "Kvadratning tomoni 6 sm. Uning yuzini toping.", a: ["24 sm²", "36 sm²", "12 sm²"], c: 1 },
            { s: "3x + 12 = 27 tenglamani yeching.", a: ["x = 5", "x = 4", "x = 6"], c: 0 },
            { s: "7 ning kubi nechaga teng?", a: ["243", "343", "49"], c: 1 },
            { s: "20 ning 15 foizini toping.", a: ["3", "4", "2.5"], c: 0 },
            { s: "Tub sonni aniqlang:", a: ["9", "15", "17"], c: 2 },
            { s: "Agar uchburchakning asosi 8 sm va balandligi 5 sm bo'lsa, uning yuzini toping.", a: ["40 sm²", "20 sm²", "15 sm²"], c: 1 },
            { s: "Eng kichik ikki xonali tub son qaysi?", a: ["10", "11", "13"], c: 1 },
            { s: "Yig'indini hisoblang: 1/2 + 1/4 = ?", a: ["3/4", "2/6", "1/3"], c: 0 },
            { s: "O'nli kasrni oddiy kasrga aylantiring: 0.25", a: ["1/5", "1/4", "2/5"], c: 1 },
            { s: "5! (5 faktorial) nechaga teng?", a: ["60", "120", "24"], c: 1 },
            { s: "Arifmetik progressiyada a1 = 3, d = 2 bo'lsa, a5 ni toping.", a: ["11", "9", "13"], c: 0 },
            { s: "Logarifm log2(16) nechaga teng?", a: ["3", "4", "5"], c: 1 },
            { s: "Geometrik progressiyada b1 = 2, q = 3 bo'lsa, b3 ni toping.", a: ["6", "12", "18"], c: 2 },
            { s: "Ikki sonning ko'paytmasi 72, ulardan biri 8 bo'lsa, ikkinchi sonni toping.", a: ["9", "7", "6"], c: 0 },
            { s: "Tengsizlikni yeching: 2x - 5 > 7", a: ["x > 6", "x > 1", "x > 12"], c: 0 },
            { s: "f(x) = 3x² funksiyaning hosilasini toping.", a: ["6x", "3x", "6x²"], c: 0 },
            { s: "Soddalashtiring: (x + 3)²", a: ["x² + 9", "x² + 6x + 9", "x² + 3x + 9"], c: 1 },
            { s: "120 sonining nechta tub ko'paytuvchisi bor (turli xil)?", a: ["2", "3", "4"], c: 1 },
            { s: "Yig'indini toping: 135 + 246", a: ["381", "371", "391"], c: 0 },
            { s: "Kvadrat tenglamaning diskriminanti D=0 bo'lsa, tenglama nechta ildizga ega?", a: ["2 ta", "1 ta", "ildizga ega emas"], c: 1 },
            { s: "Sonli ifodani hisoblang: |-15| + | -5 |", a: ["10", "20", "-20"], c: 1 },
            { s: "Proporsiyaning noma'lum hadini toping: 4/x = 12/15", a: ["5", "3", "6"], c: 0 },
            { s: "30 va 45 sonlarining eng katta umumiy bo'luvchisini (EKUB) toping.", a: ["15", "5", "9"], c: 0 },
            { s: "Sonlar o'rta arifmetigini toping: 10, 20, 30", a: ["15", "20", "25"], c: 1 }
        ]
    },
    {
        id: 'english', name: 'Ingliz tili', icon: '🇬🇧',
        q: [
            { s: "Choose the correct form: She ___ television every evening.", a: ["watch", "watches", "watching"], c: 1 },
            { s: "What is the past simple form of the verb 'go'?", a: ["gone", "went", "goes"], c: 1 },
            { s: "Identify the antonym of the word 'Beautiful':", a: ["Pretty", "Ugly", "Smart"], c: 1 },
            { s: "Fill in the blank: I have been living here ___ 2015.", a: ["since", "for", "during"], c: 0 },
            { s: "Choose the correct pronoun: This book belongs to John. It is ___ book.", a: ["him", "his", "he"], c: 1 },
            { s: "What is the plural form of 'child'?", a: ["childs", "childrens", "children"], c: 2 },
            { s: "Which sentence is in the Present Perfect tense?", a: ["I have eaten breakfast.", "I ate breakfast.", "I am eating breakfast."], c: 0 },
            { s: "Complete the conditional: If it rains, we ___ at home.", a: ["will stay", "would stay", "stayed"], c: 0 },
            { s: "Choose the correct comparative: London is ___ than Oxford.", a: ["big", "bigger", "more big"], c: 1 },
            { s: "What is the synonym of 'Huge'?", a: ["Tiny", "Large", "Heavy"], c: 1 },
            { s: "Identify the noun in the sentence: 'The cat slept soundly.'", a: ["cat", "slept", "soundly"], c: 0 },
            { s: "Fill in the article: She is ___ honest girl.", a: ["a", "an", "the"], c: 1 },
            { s: "What is the opposite of 'Generous'?", a: ["Kind", "Mean", "Lazy"], c: 1 },
            { s: "Choose the correct spelling:", a: ["Necessary", "Necesary", "Necessery"], c: 0 },
            { s: "Which modal verb expresses strong obligation?", a: ["might", "must", "can"], c: 1 },
            { s: "Fill in the gap: Look at those clouds! It ___ rain.", a: ["is going to", "will", "goes to"], c: 0 },
            { s: "What does the idiom 'Piece of cake' mean?", a: ["Very difficult", "Very delicious", "Very easy"], c: 2 },
            { s: "Choose the correct preposition: We usually meet ___ Sundays.", a: ["at", "in", "on"], c: 2 },
            { s: "What is the past participle of 'write'?", a: ["wrote", "written", "writing"], c: 1 },
            { s: "Identify the correct question form:", a: ["Where you live?", "Where do you live?", "Where live you?"], c: 1 },
            { s: "Which suffix makes a noun from the verb 'educate'?", a: ["-ion", "-ment", "-ful"], c: 0 },
            { s: "Choose the passive voice form: 'The house ___ in 1990.'", a: ["built", "was built", "is built"], c: 1 },
            { s: "What is the meaning of 'procrastinate'?", a: ["To speed up", "To delay doing something", "To complain"], c: 1 },
            { s: "Fill in the blank: Neither Susan ___ her sister was at the party.", a: ["or", "nor", "and"], c: 1 },
            { s: "Identify the adverb: 'He ran quickly to the station.'", a: ["ran", "quickly", "station"], c: 1 }
        ]
    },
    {
        id: 'physics', name: 'Fizika', icon: '⚛️',
        q: [
            { s: "Nyutonning ikkinchi qonuni formulasini ko'rsating:", a: ["F = m·a", "E = m·c²", "v = s/t"], c: 0 },
            { s: "Xalqaro birliklar sistemasida (SI) bosim birligi nima?", a: ["Joul", "Paskal", "Nyuton"], c: 1 },
            { s: "Yorug'likning vakuumdagi tezligi taxminan qancha?", a: ["300,000 km/s", "150,000 km/s", "340 m/s"], c: 0 },
            { s: "Kuchlanishni o'lchaydigan asbob qanday ataladi?", a: ["Ampermetr", "Voltmetr", "Ommetr"], c: 1 },
            { s: "Issiqlik miqdori birligi nima?", a: ["Vatt", "Joul", "Kaloriya"], c: 1 },
            { s: "Erkin tushish tezlanishi g ning qiymati Yer yuzida o'rtacha qancha?", a: ["9.8 m/s²", "8.9 m/s²", "10.5 m/s²"], c: 0 },
            { s: "Zichlik qaysi harf bilan belgilanadi?", a: ["m", "V", "ρ (ro)"], c: 2 },
            { s: "O'tkazgich qarshiligining formulasi qaysi?", a: ["R = U/I", "R = I/U", "P = UI"], c: 0 },
            { s: "Dinamika bo'limi nimani o'rganadi?", a: ["Harakat traektoriyasini", "Harakatni vujudga keltiruvchi sabablarni", "Suyuqliklar muvozanatini"], c: 1 },
            { s: "Quyoshdan Yerga energiya qaysi usulda uzatiladi?", a: ["Issiqlik o'tkazuvchanlik", "Konveksiya", "Nurlanish"], c: 2 },
            { s: "Mexanik ishning formulasi qaysi?", a: ["A = F·s", "N = A/t", "E = mgh"], c: 0 },
            { s: "Kinetik energiya formulasi qaysi?", a: ["E = mgh", "E = mv²/2", "E = kx²/2"], c: 1 },
            { s: "Transformator nima uchun xizmat qiladi?", a: ["O'zgarmas tokni o'zgaruvchan qilishga", "Kuchlanishni o'zgartirishga", "Tok kuchini o'lchashga"], c: 1 },
            { s: "Absolyut nol temperatura Selsiy shkalasida nechaga teng?", a: ["0 °C", "-273.15 °C", "-100 °C"], c: 1 },
            { s: "Yorug'likning sinish qonunini kim kashf etgan?", a: ["Nyuton", "Snellius", "Galiley"], c: 1 },
            { s: "Bosim kuchi formulasini ko'rsating.", a: ["P = F/S", "F = P·S", "S = F/P"], c: 1 },
            { s: "Gidravlik press qaysi qonunga asoslangan?", a: ["Arximed qonuni", "Paskal qonuni", "Bernulli qonuni"], c: 1 },
            { s: "Tezlikning vaqt bo'yicha hosilasi nimani beradi?", a: ["Ko'chishni", "Tezlanishni", "Kuchni"], c: 1 },
            { s: "Tovush to'lqinlari qanday muhitda tarqala olmaydi?", a: ["Havoda", "Suvda", "Vakuumda"], c: 2 },
            { s: "Molekulyar-kinetik nazariyaning asosiy tenglamasi qaysi?", a: ["p = nKT", "pV = m/M RT", "F = kx"], c: 0 },
            { s: "Elektrmagnit induksiya qonunini kim kashf etgan?", a: ["Kulon", "Faradey", "Om"], c: 1 },
            { s: "Modda miqdori birligi nima?", a: ["Kilogramm", "Mol", "Litr"], c: 1 },
            { s: "Qaysi kuch jism harakatiga har doim qarshi yo'nalgan bo'ladi?", a: ["Og'irlik kuchi", "Ishqalanish kuchi", "Elastiklik kuchi"], c: 1 },
            { s: "Ideal gaz holat tenglamasi qanday nomlanadi?", a: ["Klayperon-Mendeleev tenglamasi", "Boyl-Mariott qonuni", "Gey-Lyussak qonuni"], c: 0 },
            { s: "Yadro fizikasi nimani o'rganadi?", a: ["Molekulalarni", "Atom yadrosini va uning o'zgarishlarini", "Elektron qobiqlarini"], c: 1 }
        ]
    },
    {
        id: 'chemistry', name: 'Kimyo', icon: '🧪',
        q: [
            { s: "Suvning kimyoviy formulasini ko'rsating:", a: ["O2", "O3", "H2O"], c: 2 },
            { s: "Davriy sistemada birinchi element qaysi?", a: ["Geliy", "Vodorod", "Litay"], c: 1 },
            { s: "Osh tuzining kimyoviy nomi nima?", a: ["Natriy xlorid", "Kaliy sulfat", "Kalsiy karbonat"], c: 0 },
            { s: "Oksidlanish jarayonida element elektronni nima qiladi?", a: ["Biriktiradi", "Yo'qotadi (beradi)", "O'zgartirmaydi"], c: 1 },
            { s: "Uglevodorodlarning eng oddiy vakili qaysi?", a: ["Etan", "Metan", "Propan"], c: 1 },
            { s: "Kislotali muhitda lakmus qog'ozi qanday rangga kiradi?", a: ["Ko'k", "Qizil", "Sariq"], c: 1 },
            { s: "Olmos va grafit qaysi elementning allotropik ko'rinishi?", a: ["Kislorod", "Uglerod", "Azot"], c: 1 },
            { s: "Mendeleev davriy qonunni nechanchi yilda kashf etgan?", a: ["1869-yil", "1901-yil", "1855-yil"], c: 0 },
            { s: "Kimyoviy reaksiyani tezlashtiruvchi, lekin o'zi sarflanmaydigan modda nima?", a: ["Ingibitor", "Katalizator", "Indikator"], c: 1 },
            { s: "Havo tarkibida eng ko'p tarqalgan gaz qaysi?", a: ["Kislorod", "Azot", "Karbonat angidrid"], c: 1 },
            { s: "Sulfat kislotaning formulasini aniqlang:", a: ["HCl", "HNO3", "H2SO4"], c: 2 },
            { s: "Organik kimyo qaysi element birikmalarini o'rganadi?", a: ["Kremniy", "Uglerod", "Vodorod"], c: 1 },
            { s: "Atomning musbat zaryadlangan zarrachasi nima?", a: ["Elektron", "Neytron", "Proton"], c: 2 },
            { s: "Qaysi metall oddiy sharoitda suyuq holatda bo'ladi?", a: ["Simob", "Galiy", "Seziy"], c: 0 },
            { s: "Galkogenlar guruhiga qaysi element kiradi?", a: ["Xlor", "Kislorod", "Kaliy"], c: 1 },
            { s: "Molyar massa birligi nima?", a: ["g", "g/mol", "mol"], c: 1 },
            { s: "Neytrallanish reaksiyasi qanday moddalar o'rtasida boradi?", a: ["Tuz va suv", "Kislota va ishqor", "Metall va metallmas"], c: 1 },
            { s: "Eng kuchli metallmas element qaysi?", a: ["Kislorod", "Ftor", "Azot"], c: 1 },
            { s: "Ohaktoshning formulasi qaysi?", a: ["CaO", "Ca(OH)2", "CaCO3"], c: 2 },
            { s: "Ammiak tarkibida qaysi elementlar bor?", a: ["Azot va Vodorod", "Uglerod va Vodorod", "Oltingugurt va Kislorod"], c: 0 },
            { s: "Kovalent bog'lanish qanday hosil bo'ladi?", a: ["Elektronlar almashinuvi bilan", "Umumiy elektron jufti hosil bo'lishi bilan", "Ionlar tortishuvi bilan"], c: 1 },
            { s: "Ozon qaysi elementning shakli?", a: ["Vodorod", "Azot", "Kislorod"], c: 2 },
            { s: "Gidroliz bu nima?", a: ["Moddalarning suv bilan o'zaro ta'sir reaksiyasi", "Moddalarning parchalanishi", "Eritma hosil bo'lishi"], c: 0 },
            { s: "Mendelyev jadvalida VII guruh asosiy kichik guruh elementlari nima deb ataladi?", a: ["Ishqoriy metallar", "Galogenlar", "Inert gazlar"], c: 1 },
            { s: "Etanol qaysi sinfga tegishli?", a: ["Aldegidlar", "Spirtlar", "Kislotalar"], c: 1 }
        ]
    },
    {
        id: 'biology', name: 'Biologiya', icon: '🌿',
        q: [
            { s: "O'simliklarda fotosintez jarayoni hujayraning qaysi organoidida kechadi?", a: ["Mitoxondriya", "Xloroplast", "Ribosoma"], c: 1 },
            { s: "Odam tanasidagi eng uzun suyak qaysi?", a: ["Yelka suyagi", "Comb suyagi", "Son suyagi"], c: 2 },
            { s: "Hujayra nazariyasini kimlar yaratgan?", a: ["Darvin va Lamark", "Shleyden va Shvann", "Mendel va Morgan"], c: 1 },
            { s: "Odamda nechta qon guruhi bor?", a: ["3 ta", "4 ya", "5 ta"], c: 1 },
            { s: "Irsiyat qonuniyatlarini birinchi bo'lib kim kashf etgan?", a: ["Gregor Mendel", "Sharl Darvin", "Lui Paster"], c: 0 },
            { s: "Sitologiya nimani o'rganadi?", a: ["To'qimalarni", "Hujayrani", "A'zolarni"], c: 1 },
            { s: "Hujayraning 'energiya stansiyasi' qaysi?", a: ["Mitoxondriya", "Lizosoma", "Golji majmuasi"], c: 0 },
            { s: "DNK tarkibiga kirmaydigan azotli asos qaysi?", a: ["Urasil", "Timin", "Adenin"], c: 0 },
            { s: "Odam tana haroratini boshqaruvchi asosiy a'zo yoki qism qaysi?", a: ["Gipotalamus", "Yurak", "O'pka"], c: 0 },
            { s: "Insonda nechta xromosoma bor?", a: ["44 ta", "46 ta", "48 ta"], c: 1 },
            { s: "Baliqlar qaysi a'zosi orqali nafas oladi?", a: ["O'pka", "Jabra", "Teri"], c: 1 },
            { s: "Viruslar nima?", a: ["Hujayrasiz hayot shakllari", "Bir hujayrali organizmlar", "Bakteriyalar turi"], c: 0 },
            { s: "Botandika nimani o'rganadigan fan?", a: ["Hayvonlarni", "O'simliklarni", "Zamburug'larni"], c: 1 },
            { s: "Qonning qizil hujayralari qanday ataladi?", a: ["Leykotsitlar", "Trombotsitlar", "Eritrotsitlar"], c: 2 },
            { s: "Odam yuragi necha kamerali?", a: ["2 kamerali", "3 kamerali", "4 kamerali"], c: 2 },
            { s: "Bakteriofag nima?", a: ["Bakteriyalarni zarblovchi virus", "Foydali bakteriya", "Zamburug' turi"], c: 0 },
            { s: "Evolyutsiya ta'limoti muallifi kim?", a: ["Jan Batist Lamark", "Sharl Darvin", "Karl Linney"], c: 1 },
            { s: "Ko'zning rangdor pardasi markazidagi teshik nima?", a: ["Qorachiq", "To'r parda", "Gavhar"], c: 0 },
            { s: "Inson tanasidagi eng katta bez qaysi?", a: ["Me'da osti bezi", "Jigar", "Qalqonsimon bez"], c: 1 },
            { s: "Zamburug'lar hujayra devori qaysi moddadan iborat?", a: ["Sellyuloza", "Xitin", "Murein"], c: 1 },
            { s: "Penitsillin daxshatli dori qaysi organizmdan olingan?", a: ["Bakteriyadan", "Zamburug'dan", "O'simlikdan"], c: 1 },
            { s: "Gidra qaysi tipga kiradi?", a: ["Bo'shliqichlilar", "Yassi qurtlar", "Halkali qurtlar"], c: 0 },
            { s: "O'simlikning vegetativ a'zolarini ko'rsating.", a: ["Gul va meva", "Ildiz va poya (barg)", "Urug'"], c: 1 },
            { s: "Insonda o'ng o'pka necha bo'lakdan iborat?", a: ["2 bo'lak", "3 bo'lak", "4 bo'lak"], c: 1 },
            { s: "Ekologiya so'zining ma'nosi nima?", a: ["Uy, yashash joyi haqidagi fan", "Tabiatni muhofaza qilish", "Hayvonlar hayoti"], c: 0 }
        ]
    },
    {
        id: 'history', name: 'Tarix', icon: '🏛️',
        q: [
            { s: "Amir Temur nechanchi yilda tug'ilgan?", a: ["1336-yil", "1405-yil", "1346-yil"], c: 0 },
            { s: "Eng qadimgi yozma manba - Avesto qaysi dinga tegishli?", a: ["Buddizm", "Zardushtiylik", "Islom"], c: 1 },
            { s: "Buyuk ipak yo'li qaysi asrlarda eng gullagan davri bo'lgan?", a: ["Miloddan avvalgi II asr - Milodiy XIV asr", "V-X asrlar", "X-XV asrlar"], c: 0 },
            { s: "Miloddan avvalgi 329-yilda O'rta Osiyoga kim bostirib kelgan?", a: ["Kir II", "Doro I", "Aleksandr Makedonskiy"], c: 2 },
            { s: "Jaloliddin Manguberdi qaysi davlat hukmdori bo'lgan?", a: ["Xorazmshohlar", "G'aznaviylar", "Saljuqiylar"], c: 0 },
            { s: "O'zbekiston Respublikasining Mustaqillik kuni qachon?", a: ["1991-yil 1-sentyabr", "1991-yil 31-avgust", "1992-yil 8-dekabr"], c: 0 },
            { s: "Birinchi jahon urushi qaysi yillarda bo'lib o'tdi?", a: ["1914-1918 yillar", "1939-1945 yillar", "1905-1912 yillar"], c: 0 },
            { s: "Boburiylar sulolasiga kim asos solgan?", a: ["Zahiriddin Muhammad Bobur", "Akbarshoh", "Shoh Jahon"], c: 0 },
            { s: "Qadimgi Misr hukmdorlari nima deb atalgan?", a: ["Xon", "Fir'avn", "Qirol"], c: 1 },
            { s: "Fransiya burjua inqilobi nechanchi yilda boshlangan?", a: ["1789-yil", "1640-yil", "1812-yil"], c: 0 },
            { s: "Somoniylar davlatining poytaxti qaysi shahar bo'lgan?", a: ["Samarqand", "Buxoro", "Xiva"], c: 1 },
            { s: "Ikkinchi jahon urushi qachon tugagan?", a: ["1943-yil", "1945-yil", "1950-yil"], c: 1 },
            { s: "Rim imperiyasi qachon g'arbiy va sharqiy qismlarga bo'linib ketdi?", a: ["395-yil", "476-yil", "218-yil"], c: 0 },
            { s: "Tarix otasi deb kim tan olingan?", a: ["Aristotel", "Herodot", "Platon"], c: 1 },
            { s: "Sohibqiron Amir Temurning poytaxti qaysi shahar edi?", a: ["Kesh", "Toshkent", "Samarqand"], c: 2 },
            { s: "Al-Xorazmiy qaysi ilm maskanida mudirlik qilgan?", a: ["Baytul Hikma (Bag'dod)", "Ma'mun akademiyasi", "Ulug'bek madrasasi"], c: 0 },
            { s: "AQSh qaysi yilda mustaqillikka erishgan?", a: ["1776-yil", "1789-yil", "1865-yil"], c: 0 },
            { s: "G'aznaviylar davlatining asoschisi kim?", a: ["Alp tegin", "Sabuk tegin", "Sulton Mahmud"], c: 0 },
            { s: "Katta qonli qirg'in keltirgan 'Salb yurishlari' nima maqsadda boshlangan edi?", a: ["Quddusni ozod qilish", "Yevropani kengaytirish", "Hindistonni bosib olish"], c: 0 },
            { s: "Shayboniylar o'zbek davlatiga qachon asos solingan?", a: ["XVI asr boshida", "XIV asrda", "XII asrda"], c: 0 },
            { s: "Mirzo Ulug'bek kim bo'lgan?", a: ["Buyuk munajjim va hukmdor", "Shoir va sarkarda", "Geograf olim"], c: 0 },
            { s: "Yaqin tarixdagi SSSR davlati nechanchi yilda parchalangan?", a: ["1989-yil", "1991-yil", "1993-yil"], c: 1 },
            { s: "Qadimgi Yunonistonda Olimpiada o'yinlari ilk bor qachon o'tkazilgan?", a: ["Mil.avv. 776-yil", "Mil.avv. 500-yil", "Mil. 100-yil"], c: 0 },
            { s: "Amir Temur Yevropani kimning tahdididan qutqargan?", a: ["Boyazid Yildirim", "To'xtamshxon", "Chingizxon"], c: 0 },
            { s: "Turkiston ASSR qachon tuzilgan edi?", a: ["1918-yil", "1924-yil", "1917-yil"], c: 0 }
        ]
    },
    {
        id: 'geography', name: 'Geografiya', icon: '🌐',
        q: [
            { s: "Dunyodagi eng chuqur ko'l qaysi?", a: ["Kaspiy", "Baykal", "Viktoriya"], c: 1 },
            { s: "Eng katta materik qaysi?", a: ["Afrika", "Yevroosiyo", "Shimoliy Amerika"], c: 1 },
            { s: "O'zbekiston qaysi dengizlar o'rtasida joylashgan (yoki yaqin)?", a: ["Orol va Kaspiy", "Qora va O'rta", "Qizil va Orol"], c: 0 },
            { s: "Dunyodagi eng uzun daryo qaysi?", a: ["Amazonka", "Nil", "Missisipi"], c: 1 },
            { s: "Yaponiya poytaxti qaysi shahar?", a: ["Pekin", "Seul", "Tokio"], c: 2 },
            { s: "Eng katta okean nomi qaysi?", a: ["Atlantika", "Tinch okeani", "Hind okeani"], c: 1 },
            { s: "Afrika materigining eng baland nuqtasi qaysi?", a: ["Kilimanjaro", "Everest", "Elbrus"], c: 0 },
            { s: "Avstraliyaning poytaxti qaysi shahar?", a: ["Sidney", "Melburn", "Kanberra"], c: 2 },
            { s: "Dunyodagi eng baland tog' cho'qqisi qaysi?", a: ["K2", "Everest (Chomolungma)", "Kanchendjanga"], c: 1 },
            { s: "Ekvator chizig'ining uzunligi taxminan qancha?", a: ["40,000 km", "20,000 km", "60,000 km"], c: 0 },
            { s: "Sahroi Kabir cho'li qaysi materikda joylashgan?", a: ["Osiyo", "Afrika", "Avstraliya"], c: 1 },
            { s: "Kanada poytaxtini ko'rsating:", a: ["Ottava", "Toronto", "Vankuver"], c: 0 },
            { s: "Yer po'stining eng qalin qismi qayerda?", a: ["Okean tubida", "Tog'lar ostida", "Tekisliklarda"], c: 1 },
            { s: "Dunyodagi eng ko'p aholiga ega davlat (oxirgi statistikaga ko'ra)?", a: ["Xitoy", "Hindiston", "AQSh"], c: 1 },
            { s: "O'zbekiston nechta davlat bilan chegaradosh?", a: ["4 ta", "5 ta", "6 ta"], c: 1 },
            { s: "Litosfera nima?", a: ["Yerning havo qobig'i", "Yerning suv qobig'i", "Yerning tosh (tashqi qattiq) qobig'i"], c: 2 },
            { s: "Eng kichik materik qaysi?", a: ["Antarktida", "Avstraliya", "Janubiy Amerika"], c: 1 },
            { s: "Misr davlati qaysi daryo bo'yida joylashgan?", a: ["Frot", "Dajla", "Nil"], c: 2 },
            { s: "Atmosferaning eng quyi qatlami qanday ataladi?", a: ["Stratosfera", "Troposfera", "Mezosfera"], c: 1 },
            { s: "Dunyodagi eng baland sharshara qaysi?", a: ["Niagara", "Anxel", "Viktoriya"], c: 1 },
            { s: "Italiya davlati qaysi yarimorolda joylashgan?", a: ["Piriney", "Apennin", "Bolqon"], c: 1 },
            { s: "O'zbekistonning eng uzun daryosi qaysi?", a: ["Sirdaryo", "Amudaryo", "Zarafshon"], c: 1 },
            { s: "Eng ko'p orolga ega bo'lgan okean qaysi?", a: ["Tinch okeani", "Atlantika", "Shimoliy Muz"], c: 0 },
            { s: "Grinvich meridiani qaysi shahardan o'tadi?", a: ["Parij", "London", "Nyu-York"], c: 1 },
            { s: "Dunyodagi eng katta orol qaysi?", a: ["Madagaskar", "Grenlandiya", "Kalimantan"], c: 1 }
        ]
    },
    {
        id: 'it', name: 'Informatika', icon: '💻',
        q: [
            { s: "Dasturlashda 'Array' atamasi nimani anglatadi?", a: ["O'zgaruvchi", "Massiv", "Funksiya"], c: 1 },
            { s: "Kompyuterning asosiy miyasi hisoblangan qurilma qaysi?", a: ["Operativ xotira", "Prosesor (CPU)", "Qattiq disk (HDD)"], c: 1 },
            { s: "HTML bu nima?", a: ["Dasturlash tili", "Hujjatlarni belgilash tili (Gipermatnli)", "Ma'lumotlar bazasi"], c: 1 },
            { s: "IP manzil nima uchun xizmat qiladi?", a: ["Fayllarni siqish uchun", "Tarmoqdagi qurilmani unikal aniqlash uchun", "Sayt dizaynini yaratish uchun"], c: 1 },
            { s: "CSS tili nima uchun ishlatiladi?", a: ["Veb-sahifaga stil va dizayn berish uchun", "Ma'lumotlarni saqlash uchun", "Server kodini yozish uchun"], c: 0 },
            { s: "Quyidagilardan qaysi biri operatsion tizim EMAS?", a: ["Linux", "Google Chrome", "Windows 11"], c: 1 },
            { s: "1 Kilobayt (KB) nechaga teng?", a: ["1000 bayt", "1024 bayt", "1024 bit"], c: 1 },
            { s: "Python dasturlash tilining yaratuvchisi kim?", a: ["Brendan Eich", "Gvido van Rossum", "Dennis Ritchi"], c: 1 },
            { s: "Ma'lumotlar bazasini boshqarish uchun qaysi tildan foydalaniladi?", a: ["HTML", "SQL", "CSS"], c: 1 },
            { s: "Kompyuter o'chganda qaysi xotiradagi ma'lumotlar o'chib ketadi?", a: ["ROM", "RAM (Operativ)", "SSD"], c: 1 },
            { s: "URL so'zining ma'nosi nima?", a: ["Resursning internetdagi manzili", "Kompyuter nomi", "Fayl kengaytmasi"], c: 0 },
            { s: "Qaysi protokol internetda xavfsiz ma'lumot uzatishni ta'minlaydi?", a: ["HTTP", "HTTPS", "FTP"], c: 1 },
            { s: "JavaScript dasturlash tili asosan qayerda ishlaydi?", a: ["Faqat serverda", "Brauzerda (Klient qismida) va serverda", "Faqat mikrosxemalarda"], c: 1 },
            { s: "Algoritm nima?", a: ["Muayyan maqsadga erishish uchun ketma-ket buyruqlar to'plami", "Kompyuter dasturi", "Matematik formula"], c: 0 },
            { s: "Git nima?", a: ["Dasturlash tili", "Versiyalarni boshqarish tizimi", "Grafik muharrir"], c: 1 },
            { s: "Quyidagilardan qaysi biri obyektga yo'naltirilgan dasturlash tili (OOP)?", a: ["C", "Java", "HTML"], c: 1 },
            { s: "Kengaytmasi .exe bo'lgan fayllar qanday fayllar?", a: ["Rasm", "Bajariladigan (ishga tushadigan) dastur", "Matnli hujjat"], c: 1 },
            { s: "DNS nima vazifani bajaradi?", a: ["Domen nomlarini IP manzillarga aylantiradi", "Internet tezligini oshiradi", "Sirlarni shifrlaydi"], c: 0 },
            { s: "HTTP protokoli qaysi portdan foydalanadi (standart)?", a: ["21", "80", "443"], c: 1 },
            { s: "Sun'iy intellekt sohasida eng mashhur va keng qo'llaniladigan til qaysi?", a: ["PHP", "Python", "C++"], c: 1 },
            { s: "Fayllarni viruslardan himoya qiluvchi dasturlar guruhi qanday ataladi?", a: ["Drayverlar", "Antiviruslar", "Utitilar"], c: 1 },
            { s: "Brauzer bu — ...", a: ["Internet sahifalarini ko'rish dasturi", "Pochta xizmati", "Qidiruv tizimi"], c: 0 },
            { s: "Kriptografiya nima?", a: ["Ma'lumotlarni shifrlash va himoyalash siri", "Kompyuter grafikasi", "Tarmoq qurish usuli"], c: 0 },
            { s: "O'zgaruvchi (Variable) nima?", a: ["Qiymat saqlash uchun ajratilgan xotira sohasi", "Doimiy o'zgarmas son", "Dasturning xatosi"], c: 0 },
            { s: "Phishing (Fishing) nima?", a: ["Internetdagi firbgarlik (ma'lumotlarni o'g'irlash) turi", "Tarmoqni sozlash", "Tezkor yuklash turi"], c: 0 }
        ]
    },
    {
        id: 'onatili', name: 'Ona tili', icon: '✍️',
        q: [
            { s: "O'zbek tiliga qachon Davlat tili maqomi berilgan?", a: ["1989-yil 21-oktyabr", "1992-yil 8-dekabr", "1991-yil 1-sentyabr"], c: 0 },
            { s: "Ega va kesim gapning qanday bo'laklari hisoblanadi?", a: ["Bosh bo'laklar", "Ikkinchi darajali bo'laklar", "Ajratilgan bo'laklar"], c: 0 },
            { s: "O'zbek tilida nechta unli fonema (tovush) bor?", a: ["10 ta", "6 ta", "5 ta"], c: 1 },
            { s: "Qaysi so'z turkumi narsa va shaxsning harakatini bildiradi?", a: ["Ot", "Sifat", "Fe'l"], c: 2 },
            { s: "O'zbek alifbosida nechta harf bor (lotin yozuviga asoslangan joriy)?", a: ["26 ta", "29 ta harf va bitta belgilar birikmasi", "29 ta"], c: 2 },
            { s: "Sinonim so'zlar nima?", a: ["Ma'nodosh so'zlar", "Zid ma'noli so'zlar", "Shakldosh so'zlar"], c: 0 },
            { s: "Otonimlar (Antonimlar) nima?", a: ["Ma'nodosh", "Zid ma'noli so'zlar", "Talaffuzi bir xil"], c: 1 },
            { s: "O'zbek tilida nechta kelishik bor?", a: ["4 ta", "6 ta", "5 ta"], c: 1 },
            { s: "Qaratqich kelishigining qo'shimchasi qaysi?", a: ["-ni", "-ning", "-ga"], c: 1 },
            { s: "Fonetika bo'limi nimani o'rganadi?", a: ["Nutq tovushlarini", "So'z turkumlarini", "Gap bo'laklarini"], c: 0 },
            { s: "Yasama so'z deb nimaga aytiladi?", a: ["So'z yasovchi qo'shimcha yordamida hosil bo'lgan so'zga", "Tub so'zga", "Qo'shma so'zga"], c: 0 },
            { s: "O'zbek tilida urg'u asosan so'zning qaysi bo'g'iniga tushadi?", a: ["Birinchi bo'g'inga", "Oxirgi bo'g'inga", "O'rtadagi bo'g'inga"], c: 1 },
            { s: "Imlo xatosi bor so'zni toping:", a: ["Muborak", "Mashxur", "Mashhur"], c: 1 },
            { s: "Ko'makchi so'zlar turkumiga qaysi biri kiradi?", a: ["Bilan, uchun, orqali", "Va, ammo, biroq", "Eslatib, xolos"], c: 0 },
            { s: "Sifat so'z turkumining so'roqlari qaysi?", a: ["Kim? Nima?", "Qanday? Qanaqa?", "Nechta? Qancha?"], c: 1 },
            { s: "Sintaksis bo'limi nimani o'rganadi?", a: ["So'z turkumlarini", "So'z birikmasi va gapni", "Harflar tarixini"], c: 1 },
            { s: "Qaysi gap faqat bosh bo'laklardan iborat bo'lsa, qanday gap deyiladi?", a: ["Yalang gap", "Yoyiq gap", "Sodda gap"], c: 0 },
            { s: "O'xshatish yuklamalarini ko'rsating.", a: ["-gina, -faqat", "-dek, -day, go'yo", "-mi, -chi"], c: 1 },
            { s: "Leksikologiya nimani o'rganadi?", a: ["Tilning lug'at tarkibini (so'zlarni)", "Gap tuzilishini", "Tovushlar tizimini"], c: 0 },
            { s: "Chiqish kelishigi qo'shimchasi qaysi?", a: ["-dan", "-da", "-ni"], c: 0 },
            { s: "Paronimlar nima?", a: ["Yozilishi bir xil, ma'nosi har xil", "Aytilishi va yozilishi yaqin, lekin ma'nolari boshqa so'zlar", "Zid ma'noli"], c: 1 },
            { s: "Undov so'zlar qatnashgan qatorni ko'rsating.", a: ["Oh, voy, urra", "Chunki, agarda", "Barakalla, rahmat"], c: 0 },
            { s: "Uslubshunoslik nima?", a: ["Nutq uslublarini o'rganuvchi bo'lim", "Lug'atlar yozish san'ati", "Gap bo'laklari tizimi"], c: 0 },
            { s: "Soni bilduruvchi so'z turkumi qaysi?", a: ["Raqam", "Son", "Miqdor"], c: 1 },
            { s: "Qaysi tinish belgisi gap oxirida his-hayajonni bildirish uchun qo'yiladi?", a: ["Nuqta", "So'roq belgisi", "Undov belgisi"], c: 2 }
        ]
    },
    {
        id: 'rustili', name: 'Rus tili', icon: '🇷🇺',
        q: [
            { s: "Как правильно: 'Я ___ в школу'?", a: ["иду", "идешь", "идет"], c: 0 },
            { s: "Какое слово является существительным?", a: ["Красивый", "Книга", "Читать"], c: 1 },
            { s: "Выберите правильный перевод: 'Olma'", a: ["Груша", "Яблоко", "Слива"], c: 1 },
            { s: "Какого рода слово 'Время'?", a: ["Мужской род", "Женский род", "Средний род"], c: 2 },
            { s: "Как будет по-русски 'Rahmat'?", a: ["Пожалуйста", "Спасибо", "Привет"], c: 1 },
            { s: "Выберите антоним слова 'Большой':", a: ["Маленький", "Старый", "Хороший"], c: 0 },
            { s: "Сколько букв в русском алфавите?", a: ["30", "33", "32"], c: 1 },
            { s: "Какая из этих букв является мягким знаком?", a: ["ъ", "ь", "ы"], c: 1 },
            { s: "Выберите глагол в прошедшем времени:", a: ["Читал", "Читает", "Будет читать"], c: 0 },
            { s: "Как правильно: 'Два ___'?", a: ["стул", "стула", "стульев"], c: 1 },
            { s: "Перевод слова 'Учитель':", a: ["O'quvchi", "O'qituvchi", "Maktab"], c: 1 },
            { s: "Какое местоимение относится к 1-му лицу единственного числа?", a: ["Ты", "Он", "Я"], c: 2 },
            { s: "Выберите правильное окончание: 'Хорош___ погода'", a: ["-ая", "-ое", "-ий"], c: 0 },
            { s: "Что означает фраза 'Как дела?'", a: ["Isming nima?", "Ishlar qanday?", "Xayrli tong!"], c: 1 },
            { s: "Какое слово пишется с большой буквы всегда в начале предложения?", a: ["Любое слово", "Только имя", "Только название страны"], c: 0 },
            { s: "Найдите ошибку в слове:", a: ["Солнце", "Малако", "Корова"], c: 1 },
            { s: "Как сказать по-русски 'Xayr'?", a: ["Здравствуйте", "До свидания", "Пожалуйста"], c: 1 },
            { s: "Какое числительное означает число '5'?", a: ["Один", "Пять", "Десять"], c: 1 },
            { s: "Какое слово лишнее в ряду (животные)?", a: ["Собака", "Кошка", "Карандаш"], c: 2 },
            { s: "Выберите правильный предлог: 'Книга лежит ___ столе'.", a: ["в", "на", "к"], c: 1 },
            { s: "Что делает ученик в школе?", a: ["Спит", "Учится", "Работает"], c: 1 },
            { s: "Какое слово является прилагательным?", a: ["Быстро", "Зеленый", "Бежать"], c: 1 },
            { s: "Как правильно пишется: 'Жи-Ши пиши с буквой ___'?", a: ["Ы", "И", "Е"], c: 1 },
            { s: "Значение слова 'Здравствуйте':", a: ["Xayr", "Assalomu alaykum (Sog' bo'ling)", "Rahmat"], c: 1 },
            { s: "Какое время года идет после зимы?", a: ["Осень", "Лето", "Весна"], c: 2 }
        ]
    },
    {
        id: 'geometry', name: 'Geometriya', icon: '📐',
        q: [
            { s: "Yoy burchak necha gradusga teng?", a: ["90°", "180°", "360°"], c: 1 },
            { s: "To'g'ri burchakli uchburchakda Pifagor teoremasi qanday yoziladi?", a: ["a² + b² = c²", "a + b = c", "E = mc²"], c: 0 },
            { s: "Uchburchak ichki burchaklarining yig'indisi nechaga teng?", a: ["180°", "360°", "90°"], c: 0 },
            { s: "Doira yuzini hisoblash formulasini ko'rsating:", a: ["S = 2πR", "S = πR²", "S = a·b"], c: 1 },
            { s: "To'rtburchak ichki burchaklari yig'indisi nechaga teng?", a: ["180°", "270°", "360°"], c: 2 },
            { s: "Burchakni teng ikkiga bo'luvchi chiziq nima deb ataladi?", a: ["Mediana", "Bissektrisa", "Balandlik"], c: 1 },
            { s: "Aylananing eng katta vatari nima deb ataladi?", a: ["Radius", "Diametr", "Urinma"], c: 1 },
            { s: "Rombning barcha tomonlari qanday?", a: ["Har xil", "Teng", "Faqat qarama-qarshilari teng"], c: 1 },
            { s: "Parallel chiziqlar qayerda kesishadi?", a: ["Hech qayerda", "Markazda", "Cheksizlikda (burchak ostida)"], c: 0 },
            { s: "Uchburchakning uchidan qarama-qarshi tomonga tushirilgan va to'g'ri burchak hosil qilgan kesma nima?", a: ["Balandlik", "Mediana", "Bissektrisa"], c: 0 },
            { s: "Trapetsiyaning yuzi qanday topiladi?", a: ["S = ah", "S = (a+b)/2 · h", "S = d1·d2 / 2"], c: 1 },
            { s: "Kubning nechta yog'i (grani) bor?", a: ["4 ta", "6 ta", "8 ta"], c: 1 },
            { s: "Sinfdosh burchaklar yoki qo'shni burchaklar yig'indisi nechaga teng?", a: ["90°", "180°", "360°"], c: 1 },
            { s: "O'tkir burchak deb nimaga aytiladi?", a: ["90° dan katta burchakka", "90° dan kichik burchakka", "Faqat 45° li burchakka"], c: 1 },
            { s: "Muntazam ko'pburchak nima?", a: ["Hamma tomonlari va burchaklari teng ko'pburchak", "Faqat to'g'ri burchakli to'rtburchak", "Istalgan ko'pburchak"], c: 0 },
            { s: "Aylana uzunligi formulasi qaysi?", a: ["C = πR²", "C = 2πR", "C = πD²"], c: 1 },
            { s: "Uchburchak tomonini teng ikkiga bo'lib, qarama-qarshi uchiga boradigan chiziq nima?", a: ["Mediana", "Bissektrisa", "Balandlik"], c: 0 },
            { s: "Shar (Sfera) hajmi formulasi qaysi?", a: ["V = πR³", "V = 4/3 πR³", "V = 4πR²"], c: 1 },
            { s: "Gipotenuza qaysi uchburchakda bo'ladi?", a: ["Muntazam uchburchakda", "To'g'ri burchakli uchburchakda", "O'tmas burchakli uchburchakda"], c: 1 },
            { s: "Silindr yon sirti yuzi formulasi qaysi?", a: ["S = 2πRh", "S = πR²h", "S = πRh"], c: 0 },
            { s: "Planimetriya bo'limi nimani o'rganadi?", a: ["Fazoviy shakllarni", "Tekislikdagi shakllarni", "Faqat burchaklarni"], c: 1 },
            { s: "Sterometriya bo'limi nimani o'rganadi?", a: ["Tekislikdagi shakllarni", "Fazoviy (uch o'lchamli) shakllarni", "Chiziqlarni"], c: 1 },
            { s: "Katet nima?", a: ["To'g'ri burchakli uchburchakning to'g'ri burchagini hosil qiluvchi tomonlari", "Eng uzun tomon", "Aylana chizig'i"], c: 0 },
            { s: "Parallelogrammning qarama-qarshi burchaklari qanday bo'ladi?", a: ["Yig'indisi 90°", "O'zaro teng", "Har xil"], c: 1 },
            { s: "Konus asosi qanday shakldan iborat?", a: ["Uchburchak", "Kvadrat", "Doira"], c: 2 }
        ]
    },
    {
        id: 'astronomy', name: 'Astronomiya', icon: '🚀',
        q: [
            { s: "Biz yashayotgan galaktika nima deb ataladi?", a: ["Andromeda", "Somon Yo'li", "Triangulum"], c: 1 },
            { s: "Quyosh tizimidagi eng katta sayyora qaysi?", a: ["Saturn", "Yupiter", "Mars"], c: 1 },
            { s: "Quyoshga eng yaqin sayyora qaysi?", a: ["Venera", "Merkuriy", "Yer"], c: 1 },
            { s: "Yerning yagona tabiiy yo'ldoshi qaysi?", a: ["Mars", "Fobos", "Oy"], c: 2 },
            { s: "Qaysi sayyora o'zining ulkan halqalari bilan mashhur?", a: ["Yupiter", "Saturn", "Neptun"], c: 1 },
            { s: "Quyosh tizimida nechta sayyora bor (hozirgi rasmiy status)?", a: ["9 ta", "8 ta", "7 ta"], c: 1 },
            { s: "Yulduzlarning porlashi va energiyasi manbai nima?", a: ["Yadro sintezi (Termoyadro reaksiyasi)", "Oddiy yonish", "Kimyoviy oksidlanish"], c: 0 },
            { s: "Eng yorqin yulduz (tungi osmondagi) qaysi?", a: ["Qutb yulduzi", "Sirius", "Betelgeyze"], c: 1 },
            { s: "Yer Quyosh atrofida to'liq bir marta aylanishi uchun qancha vaqt ketadi?", a: ["1 oy", "365 yoki 366 kun (1 yil)", "24 soat"], c: 1 },
            { s: "Yorug'lik yili nima birligi?", a: ["Vaqt birligi", "Masofa birligi", "Tezlik birligi"], c: 1 },
            { s: "Qaysi olim birinchi bo'lib teleskop orqali osmonni kuzatgan?", a: ["Kopernik", "Galiley", "Kepler"], c: 1 },
            { s: "Qizil sayyora deb qaysi sayyora ataladi?", a: ["Merkuriy", "Mars", "Venera"], c: 1 },
            { s: "Quyosh tizimidagi eng issiq sayyora qaysi?", a: ["Merkuriy", "Venera", "Mars"], c: 1 },
            { s: "Geliosentrik tizim (Quyosh markazda ekanligi) nazariyasini kim yaratgan?", a: ["Ptolemey", "Nikolay Kopernik", "Iogann Kepler"], c: 1 },
            { s: "Koinot taxminan necha milliard yil oldin paydo bo'lgan (Katta portlash nazariyasi)?", a: ["4.5 milliard", "13.8 milliard", "20 milliard"], c: 1 },
            { s: "Qora tuynuk nima?", a: ["Gravitatsiyasi shunchalik kuchli ob'ektki, hatto yorug'lik ham undan qochib qutula olmaydi", "Kosmosdagi oddiy bo'shliq", "O'lik sayyora"], c: 0 },
            { s: "Quyosh qanday ob'ekt?", a: ["Katta sayyora", "Sariq pakana yulduz", "Galaktika markazi"], c: 1 },
            { s: "Yer o'z o'qi atrofida bir marta to'liq aylanishi qancha vaqt oladi?", a: ["1 yil", "1 oy", "24 soat (1 sutka)"], c: 2 },
            { s: "Supernova (O'ta yangi yulduz) nima?", a: ["Yangi tug'ilgan sayyora", "Yulduz hayotining so'nggidagi ulkan portlashi", "Kometaning parchalanishi"], c: 1 },
            { s: "Bizga eng yaqin yulduz tizimi (Quyoshdan keyin) qaysi?", a: ["Andromeda", "Alfa Sentavr", "Sirius"], c: 1 },
            { s: "Pluton nechanchi yilda sayyoralik maqomidan chiqarilib, mitti sayyora deb e'lon qilindi?", a: ["2000-yil", "2006-yil", "2010-yil"], c: 1 },
            { s: "Quyosh tutilishi qachon sodir bo'ladi?", a: ["Oy Yer va Quyosh o'rtasiga kelib qolganda", "Yer Oy va Quyosh o'rtasiga kelganda", "Mars Quyoshni to'sganda"], c: 0 },
            { s: "Kometa nima?", a: ["Muz, chang va toshdan iborat dumli kosmik jism", "Katta yulduz", "Metor parchasi"], c: 0 },
            { s: "Astronomiyada masofani o'lchash uchun ishlatiladigan 'Astronomik birlik' (AU) nima?", a: ["Yer va Oy o'rtasidagi masofa", "Yer va Quyosh o'rtasidagi masofa", "Quyosh tizimining radiusi"], c: 1 },
            { s: "Tungi osmonda yo'nalishni (Shimolni) aniqlashga yordam beradigan yulduz qaysi?", a: ["Sirius", "Vega", "Qutb yulduzi (Polaris)"], c: 2 }
        ]
    },
    {
        id: 'literature', name: 'Adabiyot', icon: '📚',
        q: [
            { s: "'O'tkan kunlar' romani muallifi kim?", a: ["Abdulla Qodiriy", "Cho'lpon", "Gafur Gulam"], c: 0 },
            { s: "Alisher Navoiy bobomiz yaratgan besh doston to'plami qanday ataladi?", a: ["Devon", "Xamsa", "Xazoyinul-maoniy"], c: 1 },
            { s: "O'zbek xalq qahramonlik eposi (dostoni) qaysi?", a: ["Alpomish", "Farhod va Shiring", "Layli va Majnun"], c: 0 },
            { s: "'Shum bola' qissasining muallifi kim?", a: ["G'afur G'ulom", "Oybek", "Said Ahmad"], c: 0 },
            { s: "G'azal mulkining sultoni deb kim e'tirof etiladi?", a: ["Zahiriddin Muhammad Bobur", "Alisher Navoiy", "Lutfiy"], c: 1 },
            { s: "'Kecha va kunduz' romani muallifi kim?", a: ["Fitrat", "Abdulla Qodiriy", "Abdulhamid Cho'lpon"], c: 2 },
            { s: "Boburning mashhur tarixiy va biografik asari qaysi?", a: ["Boburnoma", "Xat-ti Boburiy", "Mubayyin"], c: 0 },
            { s: "Erkin Vohidov qalamiga mansub mashhur dostonni ko'rsating.", a: ["Ruhlar isyoni", "O'zbegim", "O'zbekiston"], c: 0 },
            { s: "O'zbekiston Respublikasi Davlat madhiyasi matni muallifi kim?", a: ["Abdulla Oripov", "Erkin Vohidov", "Muhammad Yusuf"], c: 0 },
            { s: "Dastlabki o'zbek dramatik asari 'Padarkush' muallifi kim?", a: ["Behbudiy", "Fitrat", "Avloniy"], c: 0 },
            { s: "Jahon adabiyotining durdonasi bo'lgan 'Yetti go'zal' dostoni muallifi kim?", a: ["Alisher Navoiy", "Nizomiy Ganjaviy", "Firdavsiy"], c: 1 },
            { s: "Shoir Muhammad Yusuf she'rlarining bosh mavzusi nima?", a: ["Vatan va muhabbat", "Tarixiy janglar", "Falsafiy dunyoqarash"], c: 0 },
            { s: "Abdulla Qodiriyning ikkinchi tarixiy romani qaysi?", a: ["Mehrobdan chayon", "O'tkan kunlar", "Obid ketmon"], c: 0 },
            { s: "'Ufq' trilogiyasi muallifi qaysi adib?", a: ["Said Ahmad", "O'tkir Hoshimov", "Pirimqul Qodirov"], c: 0 },
            { s: "'Dunyoning ishlari' asari muallifi kim?", a: ["O'tkir Hoshimov", "Tohir Malik", "Xudoyberdi To'xtaboyev"], c: 0 },
            { s: "Sarguzasht janrida yozilgan 'Sariq devni minib' asari muallifi kim?", a: ["Xudoyberdi To'xtaboyev", "Anvar Obidjon", "G'afur G'ulom"], c: 0 },
            { s: "Alisher Navoiy nechanchi yilda va qayerda tug'ilgan?", a: ["1441-yil, Hirotda", "1336-yil, Keshda", "1483-yil, Andijonda"], c: 0 },
            { s: "Zulfiyaxonim qanday unvonga sazovor bo'lgan buyuk shoira?", a: ["Xalq shoiri", "O'zbekiston Qahramoni", "Xizmat ko'rsatgan madaniyat xodimi"], c: 0 },
            { s: "Jahon adabiyoti vakili Uilyam Shekspir qaysi davlat lik shoiri?", a: ["Fransiya", "Angliya", "Italiya"], c: 1 },
            { s: "'Alvido bolalik' asari muallifi kim?", a: ["Tohir Malik", "O'tkir Hoshimov", "Said Ahmad"], c: 0 },
            { s: "Dostonda lirik chekinish nima?", a: ["Muallifning o'z his-tuyg'ularini bayon qilishi", "Voqealar rivojining to'xtashi", "Qahramonning vafoti"], c: 0 },
            { s: "O'zbek adabiyotida fantastika janrining asoschilaridan biri kim?", a: ["Hojiakbar Shayxov", "Tohir Malik", "Xudoyberdi To'xtaboyev"], c: 0 },
            { s: "'Yulduzli tunlar' tarixiy romani kim haqida yozilgan?", a: ["Amir Temur", "Zahiriddin Muhammad Bobur", "Ulug'bek"], c: 1 },
            { s: "She'riyatda 'Radif' nima?", a: ["Qofiyadan keyin aynan takrorlanib keladigan so'z", "Qofiyadosh so'z", "She'rning birinchi satri"], c: 0 },
            { s: "Lirik turga mansub janrni aniqlang:", a: ["G'azal", "Hikoya", "Doston"], c: 0 }
        ]
    },
    {
        id: 'art', name: "Tasviriy san'at", icon: '🎨',
        q: [
            { s: "Mona Liza portreti muallifi kim?", a: ["Da Vinchi", "Pikasso", "Van Gog"], c: 0 },
            { s: "Uchta asosiy rangni ko'rsating:", a: ["Qizil, Sariq, Ko'k", "Yashil, Oq, Qora", "To'q sariq, Binafsha, Jigarrang"], c: 0 },
            { s: "Faqat tabiat manzaralari chiziladigan janr nima deb ataladi?", a: ["Nat扩展mort", "Portret", "Peyzaj"], c: 2 },
            { s: "Jonli jonsiz buyumlar, mevalar, gullar kompozitsiyasi chiziladigan janr qaysi?", a: ["Nat扩展mort", "Peyzaj", "Batal janri"], c: 0 },
            { s: "Haykaltaroshlik asarlari qanday usulda yaratiladi?", a: ["Faqat bo'yoq bilan", "Yorib, yo'nib, quyib yoki shakl berib (hajmli)", "Qog'ozni qirqib"], c: 1 },
            { s: "Rangtasvirda akvarel bo'yog'ining asosiy xususiyati nima?", a: ["Suvda tez erishi va shaffofligi", "Juda to'qligi va qalinligi", "Yog'li asosi borligi"], c: 0 },
            { s: "Mashhur 'To'rtburchak' (Chorniy kvadrat) asari muallifi kim?", a: ["Kazimir Malevich", "Pablo Pikasso", "Salvador Dali"], c: 0 },
            { s: "Miniatyura san'ati sohasida buyuk o'zbek rassomi kim?", a: ["Kamoliddin Behzod", "O'rol Tansiqboyev", "Akmal Nur"], c: 0 },
            { s: "Grafika san'atining asosiy vositalari nima?", a: ["Chiziq, shtrix, dog'", "Ranglar va yorug'lik", "Loy va ganch"], c: 0 },
            { s: "Kubizm yo'nalishi asoschisi bo'lgan rassom kim?", a: ["Pablo Pikasso", "Klod Mone", "Vinsent Van Gog"], c: 0 },
            { s: "Gofre yoki relyef tasvir nima?", a: ["Tekis yuzadan bir oz bo'rtib chiqqan haykaltaroshlik shakli", "Chuqur o'yilgan rasm", "Devoriy rangtasvir"], c: 0 },
            { s: "Rassom bo'yoqlarni aralashtiradigan maxsus taxtacha nima deyiladi?", a: ["Palitra", "Molbert", "Molga"], c: 0 },
            { s: "Rasm chizishda ishlatiladigan uch oyoqli maxsus dastgoh nomi nima?", a: ["Molbert", "Palitra", "Etyudnik"], c: 0 },
            { s: "Surrealizm yo'nalishining eng mashhur vakili kim?", a: ["Salvador Dali", "Rembardt", "Mikelanjelo"], c: 0 },
            { s: "O'zbekiston tabiat manzaralarini chizib 'Kuychisi' unvonini olgan rassom kim?", a: ["O'rol Tansiqboyev", "Bahodir Jalolov", "Chingiz Ahmarov"], c: 0 },
            { s: "Arxitektura (Me'morchilik) nima?", a: ["Bino va inshootlarni loyihalash hamda qurish san'ati", "Faqat ganch o'ymakorligi", "Gilam to'qish san'ati"], c: 0 },
            { s: "Inson yuz tuzilishi va qiyofasini tasvirlovchi asar qaysi janrga kiradi?", a: ["Portret", "Peyzaj", "Animallik"], c: 0 },
            { s: "Hayvonlarni tasvirlashga ixtisoslashgan san'at janri qaysi?", a: ["Animallik (Animalistik)", "Batal", "Mifologik"], c: 0 },
            { s: "Ganch o'ymakorligi qaysi san'at turiga kiradi?", a: ["Xalq amaliy san'ati", "Rangtasvir", "Grafika"], c: 0 },
            { s: "Mozaika nima?", a: ["Rangdor toshlar, shishalar yoki sopol parchalardan devorga terilgan tasvir", "Qalamda chizilgan rasm", "Yog'och o'ymakorligi"], c: 0 },
            { s: "Mikelanjelo Buonarroti kim bo'lgan?", a: ["Uyg'onish davrining buyuk haykaltaroshi va rassomi", "Zamonaviy dizayner", "Fransuz impressionisti"], c: 0 },
            { s: "Karikatura nima?", a: ["Bo'rttirib, kulgili va hajviy qilib chizilgan tasvir", "Tarixiy rasm", "Haqqoniy portret"], c: 0 },
            { s: "Yog'li bo'yoq (Maslo) nima bilan suyultiriladi?", a: ["Suv bilan", "Maxsus moy (zig'ir moyi) yoki erituvchi bilan", "Spirt bilan"], c: 1 },
            { s: "Kollaj nima?", a: ["Turli materiallarni (qog'oz, mato va b.) asosga yopishtirib yaratilgan asar", "Devorga chizilgan ulkan rasm", "Loydan yasalgan ko'za"], c: 0 },
            { s: "Rasmda yorug' va soya nima uchun kerak?", a: ["Buyumning hajmini va shaklini ko'rsatish uchun", "Ranglarni chiroyli qilish uchun", "Qog'ozni tejash uchun"], c: 0 }
        ]
    },
    {
        id: 'economy', name: 'Iqtisodiyot', icon: '📊',
        q: [
            { s: "Bozorda talab oshsa, narx qanday o'zgaradi?", a: ["Oshadi", "Kamayadi", "O'zgarmaydi"], c: 0 },
            { s: "Inflyatsiya nima?", a: ["Pul qadrsizlanishi va narx-navoning umumiy o'sishi", "Ishlab chiqarishning keskin o'sishi", "Eksport hajmining oshishi"], c: 0 },
            { s: "Yalpi Ichki Mahsulot (YIM) nima?", a: ["Bir yil davomida mamlakat hududida ishlab chiqarilgan barcha yakuniy mahsulot va xizmatlar qiymati", "Faqat chet elga sotilgan mollar", "Davlatning sof oltin zaxirasi"], c: 0 },
            { s: "Iqtisodiyotning asosiy muammosi nima?", a: ["Ehtiyojlarning cheksizligi va resurslarning cheklanganligi", "Pulning ko'pligi", "Ishsizlik yo'qligi"], c: 0 },
            { s: "Markaziy bankning asosiy vazifasi nima?", a: ["Milliy valyuta barqarorligini ta'minlash va pul siyosatini yuritish", "Aholiga kredit berish", "Tadbirkorlik bilan shug'ullanish"], c: 0 },
            { s: "Monopoliya nima?", a: ["Bozorda faqat bitta sotuvchi yoki ishlab chiqaruvchining hukmronligi", "Erkin raqobat muhiti", "Eksport va import tengligi"], c: 0 },
            { s: "Budjet taqchilligi (defitsit) nima?", a: ["Davlat xarajatlarining uning daromadlaridan ko'p bo.lishi", "Daromadning ko'payib ketishi", "Pulning yetishmasligi"], c: 0 },
            { s: "Menejment nima?", a: ["Ishlab chiqarishni boshqarish usullari va tizimi", "Mahsulotni reklama qilish", "Buxgalteriya hisobi"], c: 0 },
            { s: "Marketing nima?", a: ["Bozor qonuniyatlarini o'rganish va iste'molchi talabini qondirish san'ati", "Faqat mahsulot ishlab chiqarish", "Ishchilarga oylik berish"], c: 0 },
            { s: "O'zbekiston Respublikasining milliy valyutasi (so'm) qachon muomalaga kiritilgan?", a: ["1994-yil 1-iyul", "1991-yil 1-sentyabr", "1993-yil 15-noyabr"], c: 0 },
            { s: "Tadbirkorlikning asosiy maqsadi nima?", a: ["Foyda (daromad) olish", "Xayriya qilish", "Solig' to'lamaslik"], c: 0 },
            { s: "Devalvatsiya nima?", a: ["Milliy valyuta kursining xorijiy valyutalarga nisbatan pasayishi", "Pul qiymatining ko'tarilishi", "Oyliklarning oshishi"], c: 0 },
            { s: "Likvidlilik nima?", a: ["Aktivlarning tez va yo'qotishlarsiz pulga aylana olish xususiyati", "Kompaniya qarzi", "Yillik sof foyda"], c: 0 },
            { s: "Soliq nima?", a: ["Davlat budjetiga jismoniy va yuridik shaxslar tomonidan majburiy to'lanadigan to'lov", "Ixtiyoriy xayriya", "Kredit turi"], c: 0 },
            { s: "Eksport nima?", a: ["Mahsulot va xizmatlarni chet elga sotish", "Chet eldan mahsulot sotib olish", "Bojxona to'lovi"], c: 0 },
            { s: "Import nima?", a: ["Mahsulot va xizmatlarni chet eldan mamlakatga olib kirish", "Chet elga mol sotish", "Valyuta almashinuvi"], c: 0 },
            { s: "Ishsiz deb kimga aytiladi?", a: ["Ishlash istagi bor, faol ish qidirayotgan, lekin ish topa olmayotgan mehnatga layoqatli shaxsga", "Ishlashni xohlamaydigan odamga", "Faqat talabalarga"], c: 0 },
            { s: "Iqtisodiy resurslar guruhiga nimalar kiradi?", a: ["Yer, mehnat, kapital, tadbirkorlik qobiliyati", "Faqat pullar va oltinlar", "Bino va mashinalar"], c: 0 },
            { s: "Dividend nima?", a: ["Aksiyadorlarga kompaniya foydasidan to'lanadigan ulush", "Bank krediti foizi", "Soliq turi"], c: 0 },
            { s: "Aksiya nima?", a: ["Egasining kompaniya kapitalidagi ulushini tasdiqlovchi qimmatli qog'oz", "Qarz majburiyatnomasi", "Pul birligi"], c: 0 },
            { s: "Obligatsiya nima?", a: ["Egasiga muayyan muddatdan keyin pul va foiz qaytarilishini kafolatlovchi qarz qimmatli qog'ozi", "Kompaniya ulushi", "Soliq imtiyozi"], c: 0 },
            { s: "Bozor iqtisodiyotining asosiy harakatlantiruvchi kuchi nima?", a: ["Raqobat", "Davlat buyrug'i", "Rejali reja"], c: 0 },
            { s: "Infratuzilma (Infrastruktura) nima?", a: ["Iqtisodiyot faoliyati uchun sharoit yaratuvchi tarmoqlar (yo'l, aloqa, svet, gaz)", "Zavod ichidagi uskunalar", "Faqat banklar tizimi"], c: 0 },
            { s: "Mikroiqtisodiyot nimani o'rganadi?", a: ["Alohida korxonalar va iste'molchilar xulq-atvorini", "Butun mamlakat iqtisodiyotini", "Jahon savdo tizimini"], c: 0 },
            { s: "Makroiqtisodiyot nimani o'rganadi?", a: ["Umumtizimli muammolarni (inflyatsiya, ishsizlik, YIM o'sishi)", "Faqat kichik do'konlarni", "Bitta oila budjetini"], c: 0 }
        ]
    },
    {
        id: 'law', name: 'Huquq', icon: '⚖️',
        q: [
            { s: "O'zbekiston Respublikasi Konstitutsiyasi nechanchi yilda qabul qilingan?", a: ["1992-yil 8-dekabr", "1991-yil 31-avgust", "1995-yil 21-dekabr"], c: 0 },
            { s: "O'zbekistonda qonun chiqaruvchi oliy davlat organi qaysi?", a: ["Oliy Majlis", "Vazirlar Mahkamasi", "Oliy Sud"], c: 0 },
            { s: "Konstitutsiyaga ko'ra O'zbekiston qanday davlat?", a: ["Suveren, demokratik, huquqiy, ijtimoiy va dunyoviy", "Monarxik davlat", "Federativ respublika"], c: 0 },
            { s: "Fuqarolik huquqiy munosabatlarining sub'ektlari kimlar?", a: ["Jismoniy va yuridik shaxslar", "Faqat davlat organlari", "Faqat prokurorlar"], c: 0 },
            { s: "O'zbekiston Respublikasida prezidentlik muddati necha yil?", a: ["5 yil", "7 yil", "4 yil"], c: 1 },
            { s: "Huquqbuzarlikning og'ir turi nima deb ataladi?", a: ["Intizomiy xato", "Ma'muriy huquqbuzarlik", "Jinoyat"], c: 2 },
            { s: "O'zbekistonda sud hokimiyati kimga tegishli?", a: ["Faqat sudlarga", "Hokimliklarga", "Ichki ishlarga"], c: 0 },
            { s: "Bola huquqlari to'g'risidagi Konventsiyaga ko'ra necha yoshgacha bo'lganlar bola hisoblanadi?", a: ["16 yoshgacha", "18 yoshgacha", "21 yoshgacha"], c: 1 },
            { s: "Prezident bo'lish uchun nomzod O'zbekistonda kamida necha yil muqaddas yashagan bo'lishi kerak?", a: ["5 yil", "10 yil", "15 yil"], c: 1 },
            { s: "Nikoh yoshi O'zbekistonda erkaklar va ayollar uchun qilib belgilangan?", a: ["18 yosh", "17 yosh", "Erkaklar 18, ayollar 17 yosh"], c: 0 },
            { s: "Ma'muriy javobgarlik necha yoshdan boshlanadi?", a: ["14 yoshdan", "16 yoshdan", "18 yoshdan"], c: 1 },
            { s: "Jinoyat kodeksida ko'zda tutilgan eng og'ir jazo turi qaysi (joriy qonun)?", a: ["Umrbod ozodlikdan mahrum qilish", "O'lim jazosi", "Katta miqdorda jarima"], c: 0 },
            { s: "Inson huquqlari umumjahon deklaratsiyasi qachon qabul qilingan?", a: ["1948-yil 10-dekabr", "1945-yil 2-sentyabr", "1950-yil 1-may"], c: 0 },
            { s: "O'zbekiston Respublikasining ijro etuvchi hokimiyatini kim boshqaradi?", a: ["Prezident va Vazirlar Mahkamasi", "Oliy Majlis", "Oliy Sud"], c: 0 },
            { s: "Yuridik shaxs nima?", a: ["O'z mulkida alohida mol-mulkka ega bo'lgan korxona, tashkilot", "Faqat advokat odam", "Davlat rahbari"], c: 0 },
            { s: "Huquqiy munosabat nima?", a: ["Qonun normalari bilan tartibga solingan ijtimoiy munosabat", "Oila a'zolarining suhbati", "Do'stlar kelishuvi"], c: 0 },
            { s: "O'zbekiston Respublikasi fuqaroligini qabul qilish tartibi kim tomonidan tasdiqlanadi va hal etiladi?", a: ["Prezident tomonidan", "Bosh vazir tomonidan", "Ichki ishlar vaziri"], c: 0 },
            { s: "Pluralizm nima?", a: ["Fikrlar va qarashlarning xilma-xilligi", "Yagona davlat mafkurasi", "Qonunlarni taqiqlash"], c: 0 },
            { s: "Prezumpsiya (aybsizlik prezumpsiyasi) nima?", a: ["Shaxsning aybi qonuniy tartibda isbotlanmaguncha u aybsiz hisoblanishi", "Gumon qilinuvchini darhol qamoqqa olish", "Sudning so'nggi qarori"], c: 0 },
            { s: "Mehnat shartnomasi tuzishga necha yoshdan yo'l qo'yiladi (umumiy qoida)?", a: ["16 yoshdan", "15 yoshdan", "18 yoshdan"], c: 0 },
            { s: "Mulk huquqi nimalardan iborat?", a: ["Egalik qilish, foydalanish va tasarruf etish huquqlaridan", "Faqat uyni sotishdan", "Faqat ijaraga berishdan"], c: 0 },
            { s: "O'zbekiston Respublikasi Oliy Majlisi nechta palatadan iborat?", a: ["2 ta (Senat va Qonunchilik palatasi)", "1 ta", "3 ta"], c: 0 },
            { s: "Senat a'zolari qanday yig'iladi?", a: ["Viloyat, shahar va respublika vakillari orasidan saylanadi va tayinlanadi", "Xalq tomonidan to'g'ridan-to'g'ri", "Faqat imtihon topshirib kiradi"], c: 0 },
            { s: "Konstitutsiyaviy sud nima ish bilan shug'ullanadi?", a: ["Qonun va qarorlarning Konstitutsiyaga muvofiqligini aniqlaydi", "O'g'rilarni jazolaydi", "Ajrashganlarni ko'rib chiqadi"], c: 0 },
            { s: "Huquqning manbai nima?", a: ["Normativ-huquqiy hujjatlar, qonunlar, xalqaro shartnomalar", "Odamlarning odatlari va gaplari", "Gazeta maqolalari"], c: 0 }
        ]
    },
    {
        id: 'philosophy', name: 'Falsafa', icon: '💭',
        q: [
            { s: "'Men fikrlayapman, demak men mavjudman' iborasi kimga tegishli?", a: ["Rene Dekart", "Platon", "Aristotel"], c: 0 },
            { s: "Falsafa (Filosofiya) so'zining yunoncha ma'nosi nima?", a: ["Hikmatni sevish (donalikni sevish)", "Tabiatni o'rganish", "Inson hayoti"], c: 0 },
            { s: "Dunyoqarashning tarixiy birinchi shakli qaysi?", a: ["Mifologiya", "Din", "Falsafa"], c: 0 },
            { s: "Dialektika nima?", a: ["Rivojlanish va umumiy bog'lanishlar haqidagi ta'limot", "Faqat bahslashish san'ati", "Mantiq xatosi"], c: 0 },
            { s: "Ontologiya falsafaning qaysi bo'limi?", a: ["Borliq haqidagi ta'limot", "Bilish nazariyasi", "Inson odoblari"], c: 0 },
            { s: "Gnoseologiya falsafaning qaysi bo'limi?", a: ["Bilish nazariyasi", "Jamiyat haqidagi fan", "Estetika"], c: 0 },
            { s: "Aksiologiya nimani o'rganadi?", a: ["Qadriyatlar tizimini va tabiatini", "Mantiq qonunlarini", "Dunyoning kelib chiqishini"], c: 0 },
            { s: "Idealizm nima?", a: ["Goya, ruh yoki ong birinchi, modda esa ikkinchi deb hisoblaydigan yo'nalish", "Faqat orzu qilish", "Dinsizlik"], c: 0 },
            { s: "Materializm nima?", a: ["Modda, tabiat birinchi, ong va ruh esa moddaning rivojlanish mahsuli deb biladigan o'qish", "Faqat pulni sevish", "Ilmiy dunyoqarashsizlik"], c: 0 },
            { s: "Agnostitsizm nima?", a: ["Dunyo butunlay bilib bo'lmas deb hisoblaydigan falsafiy o'qish", "Xudoga ishonmaslik", "Rivojlanish qonuni"], c: 0 },
            { s: "Mashhur 'G'or to'g'risidagi afsona' qaysi faylasufga tegishli?", a: ["Sokrat", "Platon", "Epikur"], c: 1 },
            { s: "Aristotel qaysi buyuk sarkardaga ustozlik qilgan?", a: ["Aleksandr Makedonskiy", "Yuliy Sezar", "Kir II"], c: 0 },
            { s: "Sharq falsafasida 'Ikkinchi muallim' unvonini kim olgan?", a: ["Al-Farobiy", "Ibn Sino", "Beruniy"], c: 0 },
            { s: "Etika nimani o'rganadigan falsafiy fan?", a: ["Axloq va odob qonuniyatlarini", "Go'zallikni", "Siyosatni"], c: 0 },
            { s: "Estetika nimani o'rganadi?", a: ["Go'zallik va san'at qonuniyatlarini", "Tabiatni", "To'g'ri fikrlashni"], c: 0 },
            { s: "Sokratning asosiy falsafiy uslubi qanday nomlangan?", a: ["Mayevtika (suhbat orqali haqiqatni tug'dirish)", "Monolog", "Yozma bayon"], c: 0 },
            { s: "Zarofat (Sufiylik) falsafasining asosi nima?", a: ["Allohni qalb orqali tanish va nafsni poklash", "Boylik to'plash", "Faqat kitob yozish"], c: 0 },
            { s: "Ekzistensializm falsafasining markaziy mavzusi nima?", a: ["Inson borlig'i, erkinligi va hayotning ma'nosi", "Atomlar tuzilishi", "Davlatni boshqarish"], c: 0 },
            { s: "Stoitsizm falsafasi nimaga chaqiradi?", a: ["Hayot qiyinchiliklarini mardonavor, xotirjam va irodali kutib olishga", "Faqat rohatlanib yashashga", "Jamiyatdan qochishga"], c: 0 },
            { s: "Nitsishe falsafasida qanday g'oya ilgari surilgan?", a: ["'Komil inson' (Sverxchelovek)", "Dunyoni bilib bo'lmaslik", "Mutloq tinchlik"], c: 0 },
            { s: "Borliq tushunchasi falsafada nimani anglatadi?", a: ["Mavjud bo'lgan barcha narsalar, tabiat, inson, ong to'plami", "Faqat moddiy dunyo", "Faqat inson xayoli"], c: 0 },
            { s: "Kategoriya nima?", a: ["Eng umumiy falsafiy tushuncha (masalan: makon, zamon, sabab)", "Kitob bo'limi", "Daraja, razryad"], c: 0 },
            { s: "Substansiya falsafada nima?", a: ["Barcha narsalarning asosi, o'zgaruvchan dunyoning doimiy negizi", "Kimyoviy modda", "Inson ruhi"], c: 0 },
            { s: "Pragmatizm falsafasining asosiy mezoni nima?", a: ["Amaliy foyda va natija", "Nazariy mukammallik", "Tarixiy an'ana"], c: 0 },
            { s: "Konfusiylik falsafasi qaysi mamlakatda vujudga kelgan?", a: ["Hindiston", "Xitoy", "Yaponiya"], c: 1 }
        ]
    },
    {
        id: 'logic', name: 'Mantiq (Logika)', icon: '🧩',
        q: [
            { s: "Mantiq (Logika) fanining asoschisi kim?", a: ["Aristotel", "Platon", "Sokrat"], c: 0 },
            { s: "Mantiqan to'g'ri fikrlashning nechta asosiy qonuni bor (klassik mantiqda)?", a: ["3 ta", "4 ta", "5 ta"], c: 1 },
            { s: "Ayniyat qonunining ma'nosi nima?", a: ["Muhokama jarayonida har bir fikr o'z-o'ziga teng bo'lishi kerak (A=A)", "Ikki zid fikr ham to'g'ri", "Fikr har doim o'zgarishi kerak"], c: 0 },
            { s: "Sillogizm nima?", a: ["Ikki yoki undan ortiq hukmdan yangi hukm chiqarish (deduktiv xulosa)", "Mantiqiy xato", "Savol turi"], c: 0 },
            { s: "Tushuncha nima?", a: ["Narsalarning umumiy va muhim belgilarini aks ettiruvchi fikr shakli", "Gap, jumla", "Xulosa chiqarish"], c: 0 },
            { s: "Hukm (Mulohaza) nima?", a: ["Narsa haqida biror narsani tasdiqlovchi yoki inkor etuvchi fikr shakli", "So'z birikmasi", "Faqat savollar"], c: 0 },
            { s: "Deduksiya nima?", a: ["Umumiydan xususiyga (kichik xulosaga) qarab borish", "Xususiy holatdan umumiy qoida chiqarish", "Mantiqdan butunlay chiqish"], c: 0 },
            { s: "Induksiya nima?", a: ["Xususiy dalillardan umumiy xulosaga kelish", "Umumiydan xususiyga borish", "Fikrni rad etish"], c: 0 },
            { s: "Zidlik qonunining mohiyati nima?", a: ["Ikki o'zaro zid fikr bir vaqtda, bir xil nisbatda ham to'g'ri bo'lolmaydi", "Hamma narsa ziddiyatli", "Fikrlar bir-biriga mos kelishi shart"], c: 0 },
            { s: "Uchinchisi istisno qonuni qaysi mulohazalarga nisbatan qo'llaniladi?", a: ["Bir-birini rad etuvchi (biri to'g'ri, biri noto'g'ri, uchinchisi yo'q)", "Istalgan ikki fikrga", "Faqat matematik formulalarga"], c: 0 },
            { s: "Yetarli asos qonunini mantiqqa kim kiritgan?", a: ["Aristotel", "Leybnits", "Dekart"], c: 1 },
            { s: "Analogiya nima?", a: ["Narsalarning o'xshashligiga qarab xulosa chiqarish", "Fikrni to'g'ridan-to'g'ri rad etish", "Mantiqiy ziddiyat"], c: 0 },
            { s: "Paradoks nima?", a: ["Mantiqan to'g'ri ko'ringan, lekin ziddiyatga olib keladigan vaziyat yoki hukm", "Oddiy xato", "Matematik masala"], c: 0 },
            { s: "Sofizm nima?", a: ["Ataylab, suhbatdoshni chalg'itish uchun qilingan mantiqiy xato (yolg'on isbot)", "Haqiqiy ilm", "Falsafiy maktab"], c: 0 },
            { s: "Paralogizm nima?", a: ["Bilmasdan, bevosita xato qilingan mantiqiy chalkashlik", "Ataylab qilingan yolg'on", "To'g'ri xulosa"], c: 0 },
            { s: "Mantiqiy xulosa chiqarish (Umozaklyuchenie) nechta qismdan iborat bo'ladi kamida?", a: ["Asoslar (posilka) va yakuniy xulosa", "Faqat bitta so'z", "Uchta savol"], c: 0 },
            { s: "Mantiqiy amal: Kon'yunksiya nima?", a: ["Mantiqiy ko'paytirish ('VA' amali)", "Mantiqiy qo'shish ('YOKI' amali)", "Inkor etish ('EMAS')"], c: 0 },
            { s: "Mantiqiy amal: Diz'yunksiya nima?", a: ["Mantiqiy qo'shish ('YOKI' amali)", "Mantiqiy ko'paytirish ('VA')", "Tenglik"], c: 0 },
            { s: "Inversiya yoki inkor amali qanday so'z bilan ifodalanadi?", a: ["Emas", "Va", "Yoki"], c: 0 },
            { s: "Gipoteza nima?", a: ["Ilmiy asoslangan taxmin", "Mutloq haqiqat", "Mantiqiy xato"], c: 0 },
            { s: "Tezis nima?", a: ["Isbotlanishi kerak bo'lgan asosiy mantiqiy fikr", "Isbotlash usuli", "Tayyor xulosa"], c: 0 },
            { s: "Argument nima?", a: ["Tezisni isbotlash uchun keltiriladigan ishonchli dalil", "Bahs, urush", "Mantiqiy xulosa"], c: 0 },
            { s: "Demonstratsiya (Mantiqda) nima?", a: ["Tezis va argument o'rtasidagi mantiqiy bog'lanish, isbotlash jarayoni", "Ko'chaga chiqish", "Rasm ko'rsatish"], c: 0 },
            { s: "Mantiqiy to'plamlar va munosabatlarni grafik tasvirlash uchun qaysi diagrammadan foydalaniladi?", a: ["Eyler-Venn diagrammasi", "Pifagor jadvali", "Nyuton sxemasi"], c: 0 },
            { s: "Mantiqiy qonun buzilishi: 'Mavzuni almashtirish' nima?", a: ["Isbotlash jarayonida tezisni boshqa fikrga almashtirib qo'yish xatosi", "Kitobni almashtirish", "Tez gapirish"], c: 0 }
        ]
    }
];
